Skeleton
razielsd/chat-service pull request #1
Opened 2023-04-12 20:32 UTC by razielsd

2023-04-17 10:34 UTC, Antonboom requested changes
Привет!

Получилось посмотреть раньше окна ревью.

Хорошая работа, замечания в основном косметические.
Но хотелось бы добить установку и использование тулов.

2023-04-17 10:34 UTC, Antonboom commented on .github/workflows/ci.yml
> +      - run: go build ./cmd/chat-service
newline

https://gist.github.com/OleksiyRudenko/d51388345ea55767b7672307fe35adf3

https://www.google.com/search?q=why+newline+at+end+of+file

<img width="383" alt="Screenshot 2023-04-16 at 08 33 42" src="https://user-images.githubusercontent.com/17127404/232273112-8b1103b8-54d5-476a-bcdd-2d2d9ce527ea.png">

2023-04-17 10:34 UTC, Antonboom commented on .golangci.yml
> +    # - wastedassign
newline

2023-04-17 10:34 UTC, Antonboom commented on Taskfile.yml
> +      - go install {{.DEV_TOOLS}}
вы уверены, что это работает?

2023-04-17 10:34 UTC, Antonboom commented on Taskfile.yml
> +    - gofumpt -w internal cmd
1. забыт вызов `gci`
2. `gofumpt -w {{.GO_FILES}}`

2023-04-17 10:34 UTC, Antonboom commented on Taskfile.yml
> +    sh: echo "{{.HOME}}/Library/Caches" # FIXME
fixme актуальное?

2023-04-17 10:34 UTC, Antonboom commented on cmd/chat-service/main.go
> +	logger.Sync()
забыт `defer`
синхронизировать логер нужно при выходе из приложения

2023-04-17 10:34 UTC, Antonboom commented on internal/logger/logger.go
> +	err := LogLevel.UnmarshalText([]byte(opts.level))
интересно

2023-04-17 10:34 UTC, Antonboom commented on internal/server-debug/server.go
> +	"github.com/labstack/echo-contrib/pprof"
лайк

2023-04-17 10:34 UTC, Antonboom commented on internal/server-debug/server.go
> +	levelHandler := newApplyLogLevelHandler(lg)
почему не сделать это методом сервера?
(по аналогии)

2023-04-17 10:39 UTC, razielsd commented on Taskfile.yml
> +      - go install {{.DEV_TOOLS}}
не уверен, у меня тулы уже стояли + основная версия го 1.19 из-за этого были некоторые конфликты, проверял на синтетических данных, мне показалось, что так должно работать.

2023-04-17 10:44 UTC, razielsd commented on Taskfile.yml
> +    sh: echo "{{.HOME}}/Library/Caches" # FIXME
нет, не удалил коммент

2023-04-17 17:12 UTC, Antonboom commented on Taskfile.yml
> +      - go install {{.DEV_TOOLS}}
попробуйте сделать `rm -rf $GOBIN` и `task dev-tools:install`, `task`

2023-04-17 20:19 UTC, razielsd commented on Taskfile.yml
> +    - gofumpt -w internal cmd
не понимаю как вызвать gci

2023-04-17 20:39 UTC, razielsd commented on Taskfile.yml
> +    - gofumpt -w internal cmd
gci - golangci-lint ? он же далее вызывается

2023-04-18 04:49 UTC, Antonboom commented on Taskfile.yml
> +    - gofumpt -w internal cmd
https://github.com/daixiang0/gci#examples

2023-04-18 06:52 UTC, Antonboom approved these changes
Огонь!
Мержуем!

Для преподавателей:
https://stepik.org/review/sessions/1824882

2023-04-18 06:52 UTC, Antonboom commented on Taskfile.yml
> +    - gci write -s standard -s default -s "prefix(github.com/razielsd/chat-service)" {{.GO_FILES}}
`{{.GO_MODULE}}`?

2023-04-18 06:52 UTC, Antonboom commented on Taskfile.yml
> +    github.com/kazhuravlev/options-gen/cmd/options-gen@latest
лучше избегать latest

2023-04-18 06:54 UTC, merged